/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blas_java_Matrix */

#ifndef _Included_blas_java_Matrix
#define _Included_blas_java_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blas_java_Matrix
 * Method:    clearNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_clearNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    printNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_printNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    saveMatrixNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_saveMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    readMatrixNative
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_Matrix_readMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    ccMatrixNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_Matrix_ccMatrixNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
