/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blas_java_MatrixCalculator */

#ifndef _Included_blas_java_MatrixCalculator
#define _Included_blas_java_MatrixCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blas_java_MatrixCalculator
 * Method:    createMatrixCalculator
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_createMatrixCalculator
  (JNIEnv *, jobject);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    addNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_addNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    subNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_subNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    divNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_divNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    mulNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_mulNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    mulNative
 * Signature: (DJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_mulNative__DJ
  (JNIEnv *, jclass, jdouble, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    matrixMulNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_matrixMulNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    maxNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_maxNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    minNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_minNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    biggerNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_biggerNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    smallerNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_smallerNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    biggerNative
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_biggerNative__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    smallerNative
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_smallerNative__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    equalNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_equalNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    equalNative
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_equalNative__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    orNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_orNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    andNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_andNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    notNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_notNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    conditionNative
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_conditionNative__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    betweenNative
 * Signature: (JDD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_betweenNative
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    betweenValueNative
 * Signature: (JDD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_betweenValueNative
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    rankNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_rankNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    roundNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_roundNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    floorNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_floorNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    absNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_absNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    minusNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_minusNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    sqrtNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_sqrtNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    logNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_logNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    expNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_expNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    signNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_signNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    inverseNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_inverseNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    signedpowNative
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_signedpowNative__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    shiftNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_shiftNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    delayNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_delayNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    deltaNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_deltaNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    ratioNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_ratioNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    sumNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_sumNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    productNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_productNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMaxNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMaxNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMinNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMinNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsArgmaxNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsArgmaxNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsArgminNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsArgminNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsRankNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsRankNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMeanNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMeanNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsStdNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsStdNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsSkewnessNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsSkewnessNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsKurtosisNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsKurtosisNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCovNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCovNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCorrNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCorrNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountNaNNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountNaNNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountTrueNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountTrueNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountConsecutiveTrueNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountConsecutiveTrueNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    decayLinearNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_decayLinearNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    decayExponentialNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_decayExponentialNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    smoothByDecayLinearNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_blas_java_MatrixCalculator_smoothByDecayLinearNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    inputNaNNative
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_blas_java_MatrixCalculator_inputNaNNative
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    activateNative
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_blas_java_MatrixCalculator_activateNative
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    normalizeNative
 * Signature: (JDDD)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_normalizeNative__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    normalizeBySpecNative
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_blas_java_MatrixCalculator_normalizeBySpecNative
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    neutralizeNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_neutralizeNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    meanNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_meanNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    unifyNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_unifyNative__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    unifyByL2Native
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_unifyByL2Native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalValidPctNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalValidPctNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalAbsSumNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalAbsSumNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalMeanNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalMeanNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalVarianceNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalVarianceNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalInnerProductionNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalInnerProductionNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalCovarianceNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalCovarianceNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalCorrelationNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalCorrelationNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    DetNative
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_DetNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    InverseNative
 * Signature: (JIJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_InverseNative
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    invNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_invNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    treatNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_treatNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    diagNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_diagNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    inverseDiagNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_inverseDiagNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalInnerProductionByLongVectorNative
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_evalInnerProductionByLongVectorNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalCorrelationByLongVectorNative
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_evalCorrelationByLongVectorNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalBetaNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_evalBetaNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    cumSumNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_cumSumNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    evalBetaByLongVectorNative
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_MatrixCalculator_evalBetaByLongVectorNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    addNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_addNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    subNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_subNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    divNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_divNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    mulNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_mulNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    mulNative
 * Signature: (DJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_mulNative__DJI
  (JNIEnv *, jclass, jdouble, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    matrixMulNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_matrixMulNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    maxNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_maxNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    minNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_minNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    biggerNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_biggerNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    smallerNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_smallerNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    biggerNative
 * Signature: (JDI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_biggerNative__JDI
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    smallerNative
 * Signature: (JDI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_smallerNative__JDI
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    equalNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_equalNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    equalNative
 * Signature: (JDI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_equalNative__JDI
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    orNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_orNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    andNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_andNative__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    notNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_notNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    conditionNative
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_conditionNative__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    rankNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_rankNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    roundNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_roundNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    floorNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_floorNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    absNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_absNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    minusNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_minusNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    sqrtNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_sqrtNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    logNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_logNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    expNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_expNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    signNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_signNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    inverseNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_inverseNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    signedpowNative
 * Signature: (JDI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_signedpowNative__JDI
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    shiftNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_shiftNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    delayNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_delayNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    deltaNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_deltaNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    ratioNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_ratioNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    sumNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_sumNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    productNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_productNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMaxNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMaxNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMinNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMinNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsArgmaxNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsArgmaxNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsArgminNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsArgminNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsRankNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsRankNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsMeanNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsMeanNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsStdNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsStdNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsSkewnessNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsSkewnessNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsKurtosisNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsKurtosisNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCovNative
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCovNative__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCorrNative
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCorrNative__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountNaNNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountNaNNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountTrueNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountTrueNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    tsCountConsecutiveTrueNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_tsCountConsecutiveTrueNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    decayLinearNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_decayLinearNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    decayExponentialNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_decayExponentialNative__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    normalizeNative
 * Signature: (JDDDI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_normalizeNative__JDDDI
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    neutralizeNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_neutralizeNative__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     blas_java_MatrixCalculator
 * Method:    unifyNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixCalculator_unifyNative__JI
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
