/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blas_java_MatrixFactory */

#ifndef _Included_blas_java_MatrixFactory
#define _Included_blas_java_MatrixFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blas_java_MatrixFactory
 * Method:    getInstanceOfEmptyMatrixNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixFactory_getInstanceOfEmptyMatrixNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     blas_java_MatrixFactory
 * Method:    getInstanceOfNaNMatrixNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixFactory_getInstanceOfNaNMatrixNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     blas_java_MatrixFactory
 * Method:    getInstanceOfDiagMatrixNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixFactory_getInstanceOfDiagMatrixNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     blas_java_MatrixFactory
 * Method:    getInstanceOfRandomMatrixNative
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixFactory_getInstanceOfRandomMatrixNative
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     blas_java_MatrixFactory
 * Method:    getInstanceOfRandomLogicMatrixNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_MatrixFactory_getInstanceOfRandomLogicMatrixNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
