/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blas_java_Matrix */

#ifndef _Included_blas_java_Matrix
#define _Included_blas_java_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blas_java_Matrix
 * Method:    setElementNative
 * Signature: (IIDJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_Matrix_setElementNative
  (JNIEnv *, jobject, jint, jint, jdouble, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    getElementNative
 * Signature: (IIJ)D
 */
JNIEXPORT jdouble JNICALL Java_blas_java_Matrix_getElementNative
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    getRowVectorNative
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_getRowVectorNative
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    getColVectorNative
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_getColVectorNative
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    getNRowNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blas_java_Matrix_getNRowNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    getNColNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blas_java_Matrix_getNColNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    printNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_printNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    clearNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_clearNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    saveMatrixNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_saveMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    readMatrixNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_blas_java_Matrix_readMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_Matrix
 * Method:    ccMatrixNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_Matrix_ccMatrixNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
