/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blas_java_LogicMatrix */

#ifndef _Included_blas_java_LogicMatrix
#define _Included_blas_java_LogicMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blas_java_LogicMatrix
 * Method:    setElementNative
 * Signature: (IIZJ)V
 */
JNIEXPORT void JNICALL Java_blas_java_LogicMatrix_setElementNative
  (JNIEnv *, jobject, jint, jint, jboolean, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    getElementNative
 * Signature: (IIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_blas_java_LogicMatrix_getElementNative
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    getRowVectorNative
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_LogicMatrix_getRowVectorNative
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    getColVectorNative
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_LogicMatrix_getColVectorNative
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    getNRowNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blas_java_LogicMatrix_getNRowNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    getNColNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_blas_java_LogicMatrix_getNColNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    printNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_LogicMatrix_printNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    clearNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_blas_java_LogicMatrix_clearNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    saveMatrixNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_blas_java_LogicMatrix_saveMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    readMatrixNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_blas_java_LogicMatrix_readMatrixNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     blas_java_LogicMatrix
 * Method:    ccLogicMatrixNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_blas_java_LogicMatrix_ccLogicMatrixNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
